import { Loan, PortfolioMetrics, Alert, ESGMetric, SmartClause } from './types';

export const loans: Loan[] = [
  {
    id: 'LN-2024-001',
    borrower: 'TechCorp Industries Ltd.',
    sector: 'Technology',
    region: 'North America',
    principal: 250000000,
    interestRate: 4.75,
    tenor: 60,
    healthScore: 87,
    riskLevel: 'Low',
    status: 'Active',
    esgScore: 82,
    covenantCompliance: 95,
    nextPaymentDate: '2024-02-15',
    originationDate: '2023-02-15',
    maturityDate: '2028-02-15',
  },
  {
    id: 'LN-2024-002',
    borrower: 'GreenEnergy Solutions AG',
    sector: 'Renewable Energy',
    region: 'Europe',
    principal: 180000000,
    interestRate: 3.95,
    tenor: 84,
    healthScore: 92,
    riskLevel: 'Low',
    status: 'Active',
    esgScore: 95,
    covenantCompliance: 98,
    nextPaymentDate: '2024-03-01',
    originationDate: '2023-03-01',
    maturityDate: '2030-03-01',
  },
  {
    id: 'LN-2024-003',
    borrower: 'Global Logistics Group',
    sector: 'Transportation',
    region: 'Asia Pacific',
    principal: 125000000,
    interestRate: 5.25,
    tenor: 48,
    healthScore: 68,
    riskLevel: 'Medium',
    status: 'Active',
    esgScore: 58,
    covenantCompliance: 78,
    nextPaymentDate: '2024-02-20',
    originationDate: '2022-02-20',
    maturityDate: '2026-02-20',
  },
  {
    id: 'LN-2024-004',
    borrower: 'Manufacturing Dynamics Inc.',
    sector: 'Industrial',
    region: 'North America',
    principal: 320000000,
    interestRate: 5.50,
    tenor: 72,
    healthScore: 55,
    riskLevel: 'High',
    status: 'Active',
    esgScore: 45,
    covenantCompliance: 62,
    nextPaymentDate: '2024-02-10',
    originationDate: '2022-08-10',
    maturityDate: '2028-08-10',
  },
  {
    id: 'LN-2024-005',
    borrower: 'HealthCare Ventures plc',
    sector: 'Healthcare',
    region: 'Europe',
    principal: 95000000,
    interestRate: 4.25,
    tenor: 60,
    healthScore: 78,
    riskLevel: 'Low',
    status: 'Active',
    esgScore: 72,
    covenantCompliance: 88,
    nextPaymentDate: '2024-02-25',
    originationDate: '2023-05-25',
    maturityDate: '2028-05-25',
  },
  {
    id: 'LN-2024-006',
    borrower: 'Retail Innovations Co.',
    sector: 'Retail',
    region: 'Asia Pacific',
    principal: 75000000,
    interestRate: 6.00,
    tenor: 36,
    healthScore: 62,
    riskLevel: 'Medium',
    status: 'Active',
    esgScore: 54,
    covenantCompliance: 71,
    nextPaymentDate: '2024-02-18',
    originationDate: '2023-02-18',
    maturityDate: '2026-02-18',
  },
];

export const portfolioMetrics: PortfolioMetrics = {
  totalAUM: 1045000000,
  averageHealthScore: 74,
  activeAlerts: 8,
  totalLoans: 6,
  esgImpactScore: 68,
  covenantBreaches: 3,
};

export const alerts: Alert[] = [
  {
    id: 'ALT-001',
    loanId: 'LN-2024-004',
    severity: 'Critical',
    message: 'EBITDA covenant breach detected - Margin adjustment triggered',
    timestamp: '2024-01-10T14:23:00Z',
  },
  {
    id: 'ALT-002',
    loanId: 'LN-2024-003',
    severity: 'Warning',
    message: 'Debt-to-equity ratio approaching threshold (85% of limit)',
    timestamp: '2024-01-09T09:15:00Z',
  },
  {
    id: 'ALT-003',
    loanId: 'LN-2024-004',
    severity: 'Warning',
    message: 'ESG target missed - Carbon emissions 12% above baseline',
    timestamp: '2024-01-08T16:42:00Z',
  },
  {
    id: 'ALT-004',
    loanId: 'LN-2024-006',
    severity: 'Warning',
    message: 'Interest coverage ratio declining - Monitor cashflow',
    timestamp: '2024-01-07T11:30:00Z',
  },
  {
    id: 'ALT-005',
    loanId: 'LN-2024-001',
    severity: 'Info',
    message: 'Quarterly financial statements due in 5 days',
    timestamp: '2024-01-10T08:00:00Z',
  },
];

export const esgMetrics: ESGMetric[] = [
  {
    category: 'Carbon Intensity',
    target: 100,
    actual: 82,
    unit: 'tCO2e/M revenue',
    impactOnRate: -0.25,
  },
  {
    category: 'Renewable Energy %',
    target: 50,
    actual: 68,
    unit: '% of total',
    impactOnRate: -0.15,
  },
  {
    category: 'Water Usage',
    target: 1000,
    actual: 1150,
    unit: 'm³/M revenue',
    impactOnRate: 0.10,
  },
  {
    category: 'Waste Recycling',
    target: 75,
    actual: 81,
    unit: '% recycled',
    impactOnRate: -0.05,
  },
];

export const smartClauses: SmartClause[] = [
  {
    id: 'SC-001',
    name: 'EBITDA Covenant',
    condition: 'IF EBITDA < 50M for 2 consecutive quarters',
    action: 'THEN margin +50bps AND notify lender',
    status: 'Active',
  },
  {
    id: 'SC-002',
    name: 'Debt-to-Equity Limit',
    condition: 'IF debt/equity > 3.0',
    action: 'THEN restrict additional borrowing AND trigger review',
    status: 'Active',
  },
  {
    id: 'SC-003',
    name: 'ESG Performance Bonus',
    condition: 'IF carbon reduction > 15% YoY',
    action: 'THEN reduce margin by 25bps',
    status: 'Active',
  },
  {
    id: 'SC-004',
    name: 'Interest Coverage Floor',
    condition: 'IF EBIT/Interest < 2.5',
    action: 'THEN accelerate amortization AND increase reserves',
    status: 'Triggered',
  },
  {
    id: 'SC-005',
    name: 'Material Adverse Change',
    condition: 'IF credit rating downgrade > 2 notches',
    action: 'THEN mandatory prepayment of 25% AND renegotiate terms',
    status: 'Active',
  },
];
